# Generated by Django 5.2 on 2026-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='occupied',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
